version: "2"

services:
  grenouillebot:
    image: grenouillebot
    container_name: "grenouillebot"
    restart: always
    build:
      context: ..
      dockerfile: docker/grenouillebot/Dockerfile
    entrypoint: python3 /grenouillebot/bot/bot_application.py
